import struct

TEST_PROGRAM_SOURCE_FILE = 'test_program.c'
TEST_PROGRAM_MAIN_FUNCTION = 'main'
TEST_PROGRAM_LABEL_NAME = 'after_test_preparations'

TEST_VARIABLE_NAME = 'test_variable'
TEST_VARIABLE_ADDRESS = 0x08000000
TEST_VARIABLE_BYTES = struct.pack('=Q', 0xF123456789ABCDEF)

TEST_REGISTER_NAME = 'edx'
TEST_REGISTER_ORIGINAL_VALUE = 41
TEST_REGISTER_NEW_VALUE = 42
